### ISSUE TITLE
Compatibility with CML2.1.1

### ISSUE THREAD

**Issue by Reverendheat** [CiscoDevNet/virl2-client#7]
I am receiving "Please ensure the client version is compatible with the server version. client 2.1.0, server 2.1.1" when trying to run on the new CML 2.1.1. Is there any plan to update this to 2.1.1 soon?

**Comment by mckania0** [comment]
I've the same problem but with server in version 2.0.0 "Please ensure the client version is compatible with the server version. client 2.1.0, server 2.0.0". After client downgrade to 2.0.0b5 nothing happens while trying connect. Any solution so fat?

**Comment by rschmied** [comment]
The message is just a warning and we need to turn it down so that the warning only shows for major/minor version differences, not for patch levels, I'd say.

I'm not sure, however, what "After client downgrade to 2.0.0b5 nothing happens while trying connect" means... It doesn't work at all?  That should not be the case.  Or does that mean that the warning doesn't show anymore.  Then that IS in fact expected.

**Comment by mckania0** [comment]
In fact it works as expected on 2.0.0b5. I had some troubles with ansible-virl which use this lib, but it is other case.
